name: Delete PacketFence configuration
testcases:
- name: get_login_token
  steps:
  - type: get_login_token

- name: delete_inlinel3_network
  steps:
  - type: http
    method: DELETE
    url: '{{.pfserver_webadmin_url}}/api/v1/config/routed_network/{{.inline_l3.routed_networks}}'
    ignore_verify_ssl: true
    headers:
      "Authorization": "{{.get_login_token.result.token}}"
      "Content-Type": "application/json"
    assertions:
      - result.statuscode ShouldEqual 200

- name: configure_inlinel3_as_other
  steps:
  - type: http
    method: PATCH
    url: '{{.pfserver_webadmin_url}}/api/v1/config/interface/inlinel3'
    ignore_verify_ssl: true
    body: >-
     {
       "id": "inlinel3",
       "isClone": false,
       "isNew": false,
       "tenant_id": 1,
       "type": "none",
     }
    headers:
      "Authorization": "{{.get_login_token.result.token}}"
      "Content-Type": "application/json"
    assertions:
      - result.statuscode ShouldEqual 200

- name: delete_user_in_db
  steps:
  - type: http
    method: DELETE
    url: '{{.pfserver_webadmin_url}}/api/v1/user/iastigmate'
    ignore_verify_ssl: true
    headers:
      "Authorization": "{{.get_login_token.result.token}}"
      "Content-Type": "application/json"
    assertions:
      - result.statuscode ShouldEqual 200

- name: deconfigure_snat_interface_for_passthroughs
  steps:
  - type: http
    method: PATCH
    url: '{{.pfserver_webadmin_url}}/api/v1/config/base/network'
    ignore_verify_ssl: true
    body: >-
      {
        "interfaceSNAT":""
      }
    headers:
      "Authorization": "{{.get_login_token.result.token}}"
      "Content-Type": "application/json"
    assertions:
      - result.statuscode ShouldEqual 200
      - result.bodyjson.message ShouldEqual "Settings updated"

- name: deconfigure_snat_interface_for_inline
  steps:
  - type: http
    method: PATCH
    url: '{{.pfserver_webadmin_url}}/api/v1/config/base/inline'
    ignore_verify_ssl: true
    body: >-
     {
       "id": "inline",
       "interfaceSNAT": ""
     }
    headers:
      "Authorization": "{{.get_login_token.result.token}}"
      "Content-Type": "application/json"
    assertions:
      - result.statuscode ShouldEqual 200

- name: restart_iptables
  steps:
  - type: exec
    script: systemctl restart packetfence-iptables

    # let service restarts
  - type: exec
    script: sleep 5

- name: restart_pfdns_service
  steps:
  - type: exec
    script: systemctl restart packetfence-pfdns

    # let service restarts
  - type: exec
    script: sleep 5

- name: restart_pfdhcp_service
  steps:
  - type: exec
    script: systemctl restart packetfence-pfdhcp

    # let service restarts
  - type: exec
    script: sleep 5

- name: restart_haproxy-portal_service
  steps:
  - type: exec
    script: systemctl restart packetfence-haproxy-portal

    # let service restarts
  - type: exec
    script: sleep 5

- name: restart_keepalived_service
  steps:
  - type: exec
    script: systemctl restart packetfence-keepalived

    # let service restarts
  - type: exec
    script: sleep 5

- name: restart_pfdhcplistener_service
  steps:
  - type: exec
    script: systemctl restart packetfence-pfdhcplistener

    # let service restarts
  - type: exec
    script: sleep 5

- name: restart_pfacct_service
  steps:
  - type: exec
    script: systemctl restart packetfence-pfacct

    # let service restarts
  - type: exec
    script: sleep 5
