---
- hosts: pfservers
  name: configure Golang environment for unit tests
  become: True

  tasks:
    - name: Install qemu-system-x86 on debian
      apt:
        name: qemu-system-x86
        state: present
      when: ansible_facts['os_family'] == "Debian"

    - name: Install qemu-kvm on el8
      yum:
        name: qemu-kvm
        state: present
        enablerepo: "epel"
      when: ansible_facts['os_family'] == "RedHat"

    - name: For RHEL8Create a symbolic link for qemu-system-x86_64
      ansible.builtin.file:
        src: /usr/libexec/qemu-kvm
        dest: /usr/bin/qemu-system-x86_64
        state: link
      when: ansible_facts['os_family'] == "RedHat"
