---
# common variables to be available for all VM and also for Venom
dns_domain: 'example.lan'

# to get name of current cluster
cluster_name: '{{ lookup("env","CLUSTER_NAME") | d() }}'

cluster_vip:
  mgmt: "{{ users_vars[dict_name]['clusters'][cluster_name]['ip_mgmt'] if cluster_name|d() else '' }}"
  reg: "{{ users_vars[dict_name]['clusters'][cluster_name]['ip_reg'] if cluster_name|d() else '' }}"
  iso: "{{ users_vars[dict_name]['clusters'][cluster_name]['ip_iso'] if cluster_name|d() else '' }}"

# to get name of current PF server up in test environment
packetfence_server_name: '{{ lookup("env","PF_VM_NAMES") | default("pfel8dev", true) }}'

# lookup in Ansible inventory using name of PF server
packetfence_server_mgmt_ip: '{{ hostvars[packetfence_server_name]["mgmt_ip"] }}'

pipeline_id: '{{ lookup("env","CI_PIPELINE_ID") | default("123456789", true) }}'

# get current PacketFence minor release (X.Y)
pf_minor_release: '{{ lookup("env", "PF_MINOR_RELEASE") | default("99.9", true) }}'

